const products=[
['gpu','NVIDIA GeForce RTX Series','Gaming, dizayn va AI uchun videokartalar','RTX'],['gpu','AMD Radeon RX Series','Kuchli FPS va yuqori sifat uchun','RADEON'],['gpu','Intel Arc Series','Zamonaviy PC tizimlari uchun','ARC'],
['laptop','HP Laptop Series','O‘yin, ish va kundalik vazifalar uchun','HP'],['laptop','Acer Laptop Series','Gaming va professional noutbuklar','ACER'],['laptop','ASUS Laptop Series','ROG, TUF va boshqa seriyalar','ASUS'],['laptop','Lenovo Laptop Series','Legion va ThinkPad turkumlari','LENOVO'],['laptop','MSI Laptop Series','Yuqori quvvatli gaming noutbuklar','MSI'],['laptop','Dell Laptop Series','Ish va o‘yin uchun ishonchli yechimlar','DELL'],
['monitor','ASUS Monitor Series','Gaming va professional monitorlar','ASUS'],['monitor','Samsung Monitor Series','Odyssey va boshqa monitorlar','SAMSUNG'],['monitor','LG Monitor Series','UltraGear va UltraWide seriyalari','LG'],['monitor','Acer Monitor Series','Yuqori yangilanish tezligidagi monitorlar','ACER'],['monitor','HP Monitor Series','Ofis va uy uchun monitorlar','HP'],
['cpu','AMD Ryzen Series','Gaming va professional ishlash uchun','RYZEN'],['cpu','AMD Ryzen X3D Series','Maksimal gaming unumdorligi uchun','X3D'],['cpu','Intel Core Series','Ish, o‘yin va montaj uchun','CORE'],['cpu','Intel Core Ultra Series','Yangi avlod yuqori quvvatli protsessorlar','ULTRA'],
['accessory','Samsung SSD Series','Tezkor NVMe va SATA xotira','SSD'],['accessory','Kingston RAM Series','DDR4 va DDR5 tezkor xotira','RAM'],['accessory','Logitech Gaming Series','Sichqoncha, klaviatura va quloqchinlar','LOGI'],['accessory','Razer Gaming Series','Premium periferiyalar va aksessuarlar','RAZER'],['accessory','HyperX Series','Gaming quloqchin, klaviatura va mikrofonlar','HYPER'],['accessory','Corsair Components Series','Quvvat bloki, sovutish va korpuslar','CORSAIR'],
['printer','HP Printer Series','Lazer va rangli printerlar','HP'],['printer','Epson EcoTank Series','Siyohli va ko‘p funksiyali printerlar','EPSON'],['printer','Canon PIXMA Series','Uy va ofis uchun rangli printerlar','CANON'],['printer','Brother Printer Series','Lazer printer va MFP qurilmalari','BROTHER'],
['build','Starter Gaming PC','Boshlang‘ich gaming kompyuter yig‘ish','01'],['build','Performance Gaming PC','Kuchli o‘yinlar uchun balansli yig‘ish','02'],['build','Ultra Gaming PC','Maksimal grafik va yuqori FPS uchun','03'],['build','Creator Workstation','Dizayn, montaj va professional vazifalar uchun','04']
];
const title={all:'Barcha mahsulotlar',gpu:'Videokartalar',laptop:'Noutbuklar',monitor:'Monitorlar',cpu:'Protsessorlar',accessory:'Aksessuarlar',printer:'Printerlar',build:'Gaming PC yig‘ish'};
const grid=document.querySelector('#products'),buttons=[...document.querySelectorAll('.filter button')];
function draw(category){if(!title[category])category='all';buttons.forEach(b=>b.classList.toggle('active',b.dataset.category===category));document.querySelector('.catalog-page .catalog-lead').textContent=title[category]+' — mavjud seriyalar va professional maslahat bilan.';grid.innerHTML=products.filter(p=>category==='all'||p[0]===category).map(p=>`<article class="product"><div class="product-top"><span>${title[p[0]].toUpperCase()}</span><span>SERIES</span></div><div class="product-graphic"><span>${p[3]}</span></div><div><h3>${p[1]}</h3><p>${p[2]}</p><a href="tel:+998999882223">Mavjudligini so‘rash ↗</a></div></article>`).join('')}
buttons.forEach(b=>b.addEventListener('click',()=>{history.replaceState(null,'','?category='+b.dataset.category);draw(b.dataset.category)}));draw(new URLSearchParams(location.search).get('category')||'all');
